# coding: utf-8

"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import yt_client
from yt_client.api.default_api import DefaultApi  # noqa: E501
from yt_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = yt_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activities_get(self):
        """Test case for activities_get

        """
        pass

    def test_activities_id_get(self):
        """Test case for activities_id_get

        """
        pass

    def test_activities_page_get(self):
        """Test case for activities_page_get

        """
        pass

    def test_admin_custom_field_settings_bundles_build_get(self):
        """Test case for admin_custom_field_settings_bundles_build_get

        """
        pass

    def test_admin_custom_field_settings_bundles_build_id_delete(self):
        """Test case for admin_custom_field_settings_bundles_build_id_delete

        """
        pass

    def test_admin_custom_field_settings_bundles_build_id_get(self):
        """Test case for admin_custom_field_settings_bundles_build_id_get

        """
        pass

    def test_admin_custom_field_settings_bundles_build_id_post(self):
        """Test case for admin_custom_field_settings_bundles_build_id_post

        """
        pass

    def test_admin_custom_field_settings_bundles_build_post(self):
        """Test case for admin_custom_field_settings_bundles_build_post

        """
        pass

    def test_admin_custom_field_settings_bundles_enum_get(self):
        """Test case for admin_custom_field_settings_bundles_enum_get

        """
        pass

    def test_admin_custom_field_settings_bundles_enum_id_delete(self):
        """Test case for admin_custom_field_settings_bundles_enum_id_delete

        """
        pass

    def test_admin_custom_field_settings_bundles_enum_id_get(self):
        """Test case for admin_custom_field_settings_bundles_enum_id_get

        """
        pass

    def test_admin_custom_field_settings_bundles_enum_id_post(self):
        """Test case for admin_custom_field_settings_bundles_enum_id_post

        """
        pass

    def test_admin_custom_field_settings_bundles_enum_post(self):
        """Test case for admin_custom_field_settings_bundles_enum_post

        """
        pass

    def test_admin_custom_field_settings_bundles_owned_field_get(self):
        """Test case for admin_custom_field_settings_bundles_owned_field_get

        """
        pass

    def test_admin_custom_field_settings_bundles_owned_field_id_delete(self):
        """Test case for admin_custom_field_settings_bundles_owned_field_id_delete

        """
        pass

    def test_admin_custom_field_settings_bundles_owned_field_id_get(self):
        """Test case for admin_custom_field_settings_bundles_owned_field_id_get

        """
        pass

    def test_admin_custom_field_settings_bundles_owned_field_id_post(self):
        """Test case for admin_custom_field_settings_bundles_owned_field_id_post

        """
        pass

    def test_admin_custom_field_settings_bundles_owned_field_post(self):
        """Test case for admin_custom_field_settings_bundles_owned_field_post

        """
        pass

    def test_admin_custom_field_settings_bundles_state_get(self):
        """Test case for admin_custom_field_settings_bundles_state_get

        """
        pass

    def test_admin_custom_field_settings_bundles_state_id_delete(self):
        """Test case for admin_custom_field_settings_bundles_state_id_delete

        """
        pass

    def test_admin_custom_field_settings_bundles_state_id_get(self):
        """Test case for admin_custom_field_settings_bundles_state_id_get

        """
        pass

    def test_admin_custom_field_settings_bundles_state_id_post(self):
        """Test case for admin_custom_field_settings_bundles_state_id_post

        """
        pass

    def test_admin_custom_field_settings_bundles_state_post(self):
        """Test case for admin_custom_field_settings_bundles_state_post

        """
        pass

    def test_admin_custom_field_settings_bundles_user_get(self):
        """Test case for admin_custom_field_settings_bundles_user_get

        """
        pass

    def test_admin_custom_field_settings_bundles_user_id_aggregated_users_get(self):
        """Test case for admin_custom_field_settings_bundles_user_id_aggregated_users_get

        """
        pass

    def test_admin_custom_field_settings_bundles_user_id_delete(self):
        """Test case for admin_custom_field_settings_bundles_user_id_delete

        """
        pass

    def test_admin_custom_field_settings_bundles_user_id_get(self):
        """Test case for admin_custom_field_settings_bundles_user_id_get

        """
        pass

    def test_admin_custom_field_settings_bundles_user_id_groups_get(self):
        """Test case for admin_custom_field_settings_bundles_user_id_groups_get

        """
        pass

    def test_admin_custom_field_settings_bundles_user_id_groups_post(self):
        """Test case for admin_custom_field_settings_bundles_user_id_groups_post

        """
        pass

    def test_admin_custom_field_settings_bundles_user_id_groups_user_group_id_delete(self):
        """Test case for admin_custom_field_settings_bundles_user_id_groups_user_group_id_delete

        """
        pass

    def test_admin_custom_field_settings_bundles_user_id_groups_user_group_id_get(self):
        """Test case for admin_custom_field_settings_bundles_user_id_groups_user_group_id_get

        """
        pass

    def test_admin_custom_field_settings_bundles_user_id_individuals_get(self):
        """Test case for admin_custom_field_settings_bundles_user_id_individuals_get

        """
        pass

    def test_admin_custom_field_settings_bundles_user_id_individuals_post(self):
        """Test case for admin_custom_field_settings_bundles_user_id_individuals_post

        """
        pass

    def test_admin_custom_field_settings_bundles_user_id_individuals_user_id_delete(self):
        """Test case for admin_custom_field_settings_bundles_user_id_individuals_user_id_delete

        """
        pass

    def test_admin_custom_field_settings_bundles_user_id_individuals_user_id_get(self):
        """Test case for admin_custom_field_settings_bundles_user_id_individuals_user_id_get

        """
        pass

    def test_admin_custom_field_settings_bundles_user_id_post(self):
        """Test case for admin_custom_field_settings_bundles_user_id_post

        """
        pass

    def test_admin_custom_field_settings_bundles_user_post(self):
        """Test case for admin_custom_field_settings_bundles_user_post

        """
        pass

    def test_admin_custom_field_settings_bundles_version_get(self):
        """Test case for admin_custom_field_settings_bundles_version_get

        """
        pass

    def test_admin_custom_field_settings_bundles_version_id_delete(self):
        """Test case for admin_custom_field_settings_bundles_version_id_delete

        """
        pass

    def test_admin_custom_field_settings_bundles_version_id_get(self):
        """Test case for admin_custom_field_settings_bundles_version_id_get

        """
        pass

    def test_admin_custom_field_settings_bundles_version_id_post(self):
        """Test case for admin_custom_field_settings_bundles_version_id_post

        """
        pass

    def test_admin_custom_field_settings_bundles_version_post(self):
        """Test case for admin_custom_field_settings_bundles_version_post

        """
        pass

    def test_admin_custom_field_settings_custom_fields_get(self):
        """Test case for admin_custom_field_settings_custom_fields_get

        """
        pass

    def test_admin_custom_field_settings_custom_fields_id_delete(self):
        """Test case for admin_custom_field_settings_custom_fields_id_delete

        """
        pass

    def test_admin_custom_field_settings_custom_fields_id_field_defaults_get(self):
        """Test case for admin_custom_field_settings_custom_fields_id_field_defaults_get

        """
        pass

    def test_admin_custom_field_settings_custom_fields_id_field_defaults_post(self):
        """Test case for admin_custom_field_settings_custom_fields_id_field_defaults_post

        """
        pass

    def test_admin_custom_field_settings_custom_fields_id_get(self):
        """Test case for admin_custom_field_settings_custom_fields_id_get

        """
        pass

    def test_admin_custom_field_settings_custom_fields_id_instances_get(self):
        """Test case for admin_custom_field_settings_custom_fields_id_instances_get

        """
        pass

    def test_admin_custom_field_settings_custom_fields_id_post(self):
        """Test case for admin_custom_field_settings_custom_fields_id_post

        """
        pass

    def test_admin_custom_field_settings_custom_fields_post(self):
        """Test case for admin_custom_field_settings_custom_fields_post

        """
        pass

    def test_admin_custom_field_settings_types_get(self):
        """Test case for admin_custom_field_settings_types_get

        """
        pass

    def test_admin_database_backup_backups_get(self):
        """Test case for admin_database_backup_backups_get

        """
        pass

    def test_admin_database_backup_backups_id_get(self):
        """Test case for admin_database_backup_backups_id_get

        """
        pass

    def test_admin_database_backup_settings_backup_status_get(self):
        """Test case for admin_database_backup_settings_backup_status_get

        """
        pass

    def test_admin_database_backup_settings_get(self):
        """Test case for admin_database_backup_settings_get

        """
        pass

    def test_admin_database_backup_settings_post(self):
        """Test case for admin_database_backup_settings_post

        """
        pass

    def test_admin_global_settings_appearance_settings_get(self):
        """Test case for admin_global_settings_appearance_settings_get

        """
        pass

    def test_admin_global_settings_appearance_settings_post(self):
        """Test case for admin_global_settings_appearance_settings_post

        """
        pass

    def test_admin_global_settings_get(self):
        """Test case for admin_global_settings_get

        """
        pass

    def test_admin_global_settings_license_get(self):
        """Test case for admin_global_settings_license_get

        """
        pass

    def test_admin_global_settings_license_post(self):
        """Test case for admin_global_settings_license_post

        """
        pass

    def test_admin_global_settings_locale_settings_get(self):
        """Test case for admin_global_settings_locale_settings_get

        """
        pass

    def test_admin_global_settings_locale_settings_post(self):
        """Test case for admin_global_settings_locale_settings_post

        """
        pass

    def test_admin_global_settings_notification_settings_get(self):
        """Test case for admin_global_settings_notification_settings_get

        """
        pass

    def test_admin_global_settings_notification_settings_post(self):
        """Test case for admin_global_settings_notification_settings_post

        """
        pass

    def test_admin_global_settings_post(self):
        """Test case for admin_global_settings_post

        """
        pass

    def test_admin_global_settings_rest_settings_get(self):
        """Test case for admin_global_settings_rest_settings_get

        """
        pass

    def test_admin_global_settings_rest_settings_post(self):
        """Test case for admin_global_settings_rest_settings_post

        """
        pass

    def test_admin_global_settings_system_settings_get(self):
        """Test case for admin_global_settings_system_settings_get

        """
        pass

    def test_admin_global_settings_system_settings_post(self):
        """Test case for admin_global_settings_system_settings_post

        """
        pass

    def test_admin_projects_get(self):
        """Test case for admin_projects_get

        """
        pass

    def test_admin_projects_id_custom_fields_get(self):
        """Test case for admin_projects_id_custom_fields_get

        """
        pass

    def test_admin_projects_id_custom_fields_post(self):
        """Test case for admin_projects_id_custom_fields_post

        """
        pass

    def test_admin_projects_id_custom_fields_project_custom_field_id_delete(self):
        """Test case for admin_projects_id_custom_fields_project_custom_field_id_delete

        """
        pass

    def test_admin_projects_id_custom_fields_project_custom_field_id_get(self):
        """Test case for admin_projects_id_custom_fields_project_custom_field_id_get

        """
        pass

    def test_admin_projects_id_custom_fields_project_custom_field_id_post(self):
        """Test case for admin_projects_id_custom_fields_project_custom_field_id_post

        """
        pass

    def test_admin_projects_id_delete(self):
        """Test case for admin_projects_id_delete

        """
        pass

    def test_admin_projects_id_get(self):
        """Test case for admin_projects_id_get

        """
        pass

    def test_admin_projects_id_issues_get(self):
        """Test case for admin_projects_id_issues_get

        """
        pass

    def test_admin_projects_id_issues_issue_id_delete(self):
        """Test case for admin_projects_id_issues_issue_id_delete

        """
        pass

    def test_admin_projects_id_issues_issue_id_get(self):
        """Test case for admin_projects_id_issues_issue_id_get

        """
        pass

    def test_admin_projects_id_issues_issue_id_post(self):
        """Test case for admin_projects_id_issues_issue_id_post

        """
        pass

    def test_admin_projects_id_issues_post(self):
        """Test case for admin_projects_id_issues_post

        """
        pass

    def test_admin_projects_id_post(self):
        """Test case for admin_projects_id_post

        """
        pass

    def test_admin_projects_id_time_tracking_settings_get(self):
        """Test case for admin_projects_id_time_tracking_settings_get

        """
        pass

    def test_admin_projects_id_time_tracking_settings_post(self):
        """Test case for admin_projects_id_time_tracking_settings_post

        """
        pass

    def test_admin_projects_id_time_tracking_settings_work_item_types_get(self):
        """Test case for admin_projects_id_time_tracking_settings_work_item_types_get

        """
        pass

    def test_admin_projects_id_time_tracking_settings_work_item_types_post(self):
        """Test case for admin_projects_id_time_tracking_settings_work_item_types_post

        """
        pass

    def test_admin_projects_id_time_tracking_settings_work_item_types_work_item_type_id_delete(self):
        """Test case for admin_projects_id_time_tracking_settings_work_item_types_work_item_type_id_delete

        """
        pass

    def test_admin_projects_id_time_tracking_settings_work_item_types_work_item_type_id_get(self):
        """Test case for admin_projects_id_time_tracking_settings_work_item_types_work_item_type_id_get

        """
        pass

    def test_admin_projects_post(self):
        """Test case for admin_projects_post

        """
        pass

    def test_admin_telemetry_get(self):
        """Test case for admin_telemetry_get

        """
        pass

    def test_admin_time_tracking_settings_get(self):
        """Test case for admin_time_tracking_settings_get

        """
        pass

    def test_admin_time_tracking_settings_work_item_types_get(self):
        """Test case for admin_time_tracking_settings_work_item_types_get

        """
        pass

    def test_admin_time_tracking_settings_work_item_types_post(self):
        """Test case for admin_time_tracking_settings_work_item_types_post

        """
        pass

    def test_admin_time_tracking_settings_work_item_types_work_item_type_id_delete(self):
        """Test case for admin_time_tracking_settings_work_item_types_work_item_type_id_delete

        """
        pass

    def test_admin_time_tracking_settings_work_item_types_work_item_type_id_get(self):
        """Test case for admin_time_tracking_settings_work_item_types_work_item_type_id_get

        """
        pass

    def test_admin_time_tracking_settings_work_item_types_work_item_type_id_post(self):
        """Test case for admin_time_tracking_settings_work_item_types_work_item_type_id_post

        """
        pass

    def test_admin_time_tracking_settings_work_time_settings_get(self):
        """Test case for admin_time_tracking_settings_work_time_settings_get

        """
        pass

    def test_admin_time_tracking_settings_work_time_settings_post(self):
        """Test case for admin_time_tracking_settings_work_time_settings_post

        """
        pass

    def test_agiles_get(self):
        """Test case for agiles_get

        """
        pass

    def test_agiles_id_delete(self):
        """Test case for agiles_id_delete

        """
        pass

    def test_agiles_id_get(self):
        """Test case for agiles_id_get

        """
        pass

    def test_agiles_id_post(self):
        """Test case for agiles_id_post

        """
        pass

    def test_agiles_id_sprints_get(self):
        """Test case for agiles_id_sprints_get

        """
        pass

    def test_agiles_id_sprints_post(self):
        """Test case for agiles_id_sprints_post

        """
        pass

    def test_agiles_id_sprints_sprint_id_delete(self):
        """Test case for agiles_id_sprints_sprint_id_delete

        """
        pass

    def test_agiles_id_sprints_sprint_id_get(self):
        """Test case for agiles_id_sprints_sprint_id_get

        """
        pass

    def test_agiles_id_sprints_sprint_id_post(self):
        """Test case for agiles_id_sprints_sprint_id_post

        """
        pass

    def test_agiles_post(self):
        """Test case for agiles_post

        """
        pass

    def test_groups_get(self):
        """Test case for groups_get

        """
        pass

    def test_groups_id_get(self):
        """Test case for groups_id_get

        """
        pass

    def test_issue_link_types_get(self):
        """Test case for issue_link_types_get

        """
        pass

    def test_issue_link_types_id_delete(self):
        """Test case for issue_link_types_id_delete

        """
        pass

    def test_issue_link_types_id_get(self):
        """Test case for issue_link_types_id_get

        """
        pass

    def test_issue_link_types_id_post(self):
        """Test case for issue_link_types_id_post

        """
        pass

    def test_issue_link_types_post(self):
        """Test case for issue_link_types_post

        """
        pass

    def test_issue_tags_get(self):
        """Test case for issue_tags_get

        """
        pass

    def test_issue_tags_id_delete(self):
        """Test case for issue_tags_id_delete

        """
        pass

    def test_issue_tags_id_get(self):
        """Test case for issue_tags_id_get

        """
        pass

    def test_issue_tags_id_issues_get(self):
        """Test case for issue_tags_id_issues_get

        """
        pass

    def test_issue_tags_id_post(self):
        """Test case for issue_tags_id_post

        """
        pass

    def test_issue_tags_post(self):
        """Test case for issue_tags_post

        """
        pass

    def test_issues_get(self):
        """Test case for issues_get

        """
        pass

    def test_issues_id_activities_activity_item_id_get(self):
        """Test case for issues_id_activities_activity_item_id_get

        """
        pass

    def test_issues_id_activities_get(self):
        """Test case for issues_id_activities_get

        """
        pass

    def test_issues_id_activities_page_get(self):
        """Test case for issues_id_activities_page_get

        """
        pass

    def test_issues_id_attachments_get(self):
        """Test case for issues_id_attachments_get

        """
        pass

    def test_issues_id_attachments_issue_attachment_id_delete(self):
        """Test case for issues_id_attachments_issue_attachment_id_delete

        """
        pass

    def test_issues_id_attachments_issue_attachment_id_get(self):
        """Test case for issues_id_attachments_issue_attachment_id_get

        """
        pass

    def test_issues_id_attachments_issue_attachment_id_post(self):
        """Test case for issues_id_attachments_issue_attachment_id_post

        """
        pass

    def test_issues_id_attachments_post(self):
        """Test case for issues_id_attachments_post

        """
        pass

    def test_issues_id_comments_get(self):
        """Test case for issues_id_comments_get

        """
        pass

    def test_issues_id_comments_issue_comment_id_delete(self):
        """Test case for issues_id_comments_issue_comment_id_delete

        """
        pass

    def test_issues_id_comments_issue_comment_id_get(self):
        """Test case for issues_id_comments_issue_comment_id_get

        """
        pass

    def test_issues_id_comments_issue_comment_id_post(self):
        """Test case for issues_id_comments_issue_comment_id_post

        """
        pass

    def test_issues_id_comments_post(self):
        """Test case for issues_id_comments_post

        """
        pass

    def test_issues_id_custom_fields_get(self):
        """Test case for issues_id_custom_fields_get

        """
        pass

    def test_issues_id_custom_fields_issue_custom_field_id_get(self):
        """Test case for issues_id_custom_fields_issue_custom_field_id_get

        """
        pass

    def test_issues_id_custom_fields_issue_custom_field_id_post(self):
        """Test case for issues_id_custom_fields_issue_custom_field_id_post

        """
        pass

    def test_issues_id_delete(self):
        """Test case for issues_id_delete

        """
        pass

    def test_issues_id_get(self):
        """Test case for issues_id_get

        """
        pass

    def test_issues_id_links_get(self):
        """Test case for issues_id_links_get

        """
        pass

    def test_issues_id_links_issue_link_id_get(self):
        """Test case for issues_id_links_issue_link_id_get

        """
        pass

    def test_issues_id_links_issue_link_id_issues_get(self):
        """Test case for issues_id_links_issue_link_id_issues_get

        """
        pass

    def test_issues_id_links_issue_link_id_issues_issue_id_delete(self):
        """Test case for issues_id_links_issue_link_id_issues_issue_id_delete

        """
        pass

    def test_issues_id_links_issue_link_id_issues_post(self):
        """Test case for issues_id_links_issue_link_id_issues_post

        """
        pass

    def test_issues_id_post(self):
        """Test case for issues_id_post

        """
        pass

    def test_issues_id_project_get(self):
        """Test case for issues_id_project_get

        """
        pass

    def test_issues_id_project_post(self):
        """Test case for issues_id_project_post

        """
        pass

    def test_issues_id_time_tracking_get(self):
        """Test case for issues_id_time_tracking_get

        """
        pass

    def test_issues_id_time_tracking_work_items_get(self):
        """Test case for issues_id_time_tracking_work_items_get

        """
        pass

    def test_issues_id_time_tracking_work_items_issue_work_item_id_delete(self):
        """Test case for issues_id_time_tracking_work_items_issue_work_item_id_delete

        """
        pass

    def test_issues_id_time_tracking_work_items_issue_work_item_id_get(self):
        """Test case for issues_id_time_tracking_work_items_issue_work_item_id_get

        """
        pass

    def test_issues_id_time_tracking_work_items_issue_work_item_id_post(self):
        """Test case for issues_id_time_tracking_work_items_issue_work_item_id_post

        """
        pass

    def test_issues_id_time_tracking_work_items_post(self):
        """Test case for issues_id_time_tracking_work_items_post

        """
        pass

    def test_issues_post(self):
        """Test case for issues_post

        """
        pass

    def test_saved_queries_get(self):
        """Test case for saved_queries_get

        """
        pass

    def test_saved_queries_id_delete(self):
        """Test case for saved_queries_id_delete

        """
        pass

    def test_saved_queries_id_get(self):
        """Test case for saved_queries_id_get

        """
        pass

    def test_saved_queries_id_post(self):
        """Test case for saved_queries_id_post

        """
        pass

    def test_saved_queries_post(self):
        """Test case for saved_queries_post

        """
        pass

    def test_users_get(self):
        """Test case for users_get

        """
        pass

    def test_users_id_get(self):
        """Test case for users_id_get

        """
        pass

    def test_users_id_profiles_general_get(self):
        """Test case for users_id_profiles_general_get

        """
        pass

    def test_users_id_profiles_general_post(self):
        """Test case for users_id_profiles_general_post

        """
        pass

    def test_users_id_profiles_notifications_get(self):
        """Test case for users_id_profiles_notifications_get

        """
        pass

    def test_users_id_profiles_notifications_post(self):
        """Test case for users_id_profiles_notifications_post

        """
        pass

    def test_users_id_profiles_timetracking_get(self):
        """Test case for users_id_profiles_timetracking_get

        """
        pass

    def test_users_id_profiles_timetracking_post(self):
        """Test case for users_id_profiles_timetracking_post

        """
        pass

    def test_users_id_saved_queries_get(self):
        """Test case for users_id_saved_queries_get

        """
        pass

    def test_users_id_tags_get(self):
        """Test case for users_id_tags_get

        """
        pass

    def test_users_me_get(self):
        """Test case for users_me_get

        """
        pass

    def test_work_items_get(self):
        """Test case for work_items_get

        """
        pass

    def test_work_items_id_get(self):
        """Test case for work_items_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
